[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]

# Extra output to include in the contractâ€™s artifact.
# https://book.getfoundry.sh/reference/config/solidity-compiler#extra_output
#
# See `outputSelection` property in Input Description
# https://docs.soliditylang.org/en/latest/using-the-compiler.html#input-description
extra_output = [
    # Used by tests to locate variable's slots and avoid hardcoding them
    "storageLayout", # Slots, offsets and types of the contract's state variables in storage
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
