# SPDX-License-Identifier: Apache-2.0
name: EVM functional testing
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash
permissions:
  contents: read

env:
  SOLO_VERSION: 0.48.0
  SOLO_CLUSTER_NAME: solo-evm-e2e
  SOLO_NAMESPACE: solo-evm-e2e
  SOLO_DEPLOYMENT: solo-evm-deployment
  SOLO_CLUSTER_SETUP_NAMESPACE: solo-setup
  GRADLE_EXEC: ionice -c 2 -n 2 nice -n 19 ./gradlew
  CONSENSUS_NODE_DIR: "../../hiero-consensus-node"
  APP_PROPERTIES_PATH: "evm-testing/evm-functional-testing/local/application.properties"
  # alias f70febf7420398c3892ce79fdc393c1a5487ad27
  TEST_ACCOUNT_ECDSA_PRIVATE_KEY_DER_1: 3030020100300706052b8104000a04220420de78ff4e5e77ec2bf28ef7b446d4bec66e06d39b6e6967864b2bf3d6153f3e68
  # alias dbe82db504ca6701fbe59e638ceaddbdb691067b
  TEST_ACCOUNT_ECDSA_PRIVATE_KEY_DER_2: 3030020100300706052b8104000a04220420748634984b480c75456a68ea88f31609cd3091e012e2834948a6da317b727c04
  # alias 84b4d82e6ed64102d0faa6c29bf4e9f541db442f
  TEST_ACCOUNT_ECDSA_PRIVATE_KEY_DER_3: 3030020100300706052b8104000a042204203bcb2fbd18610f44eda2bfd58df63d053e2a6b165617a2ef5e5cca079e0c588a
  TEST_ACCOUNT_HBAR_AMOUNT: 10000

jobs:
  evm-functional-testing:
    name: Standard
    runs-on: smart-contracts-linux-medium
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Consensus Node
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: hiero-ledger/hiero-consensus-node
          ref: main
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00  # v4.7.1
        with:
          distribution: temurin
          java-version: 21.0.6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1
        with:
          cache-read-only: false

      - name: Build hiero-consensus-node
        run: '${GRADLE_EXEC} assemble'

      - name: Setup NodeJS Environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: evm-testing

      - name: Install npm testing dependencies
        run: npm ci
        working-directory: evm-testing/system-contract-testing

      - name: Install Solo
        run: npm install -g @hashgraph/solo@${SOLO_VERSION}

      - name: Setup Kind
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          install_only: true
          node_image: >-
            kindest/node:v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30
          version: v0.26.0
          kubectl_version: v1.31.4
          verbosity: 3
          wait: 120s

      - name: Configure and run solo
        id: run_solo
        run: |
          kind create cluster -n "${SOLO_CLUSTER_NAME}"
          solo init
          solo cluster-ref config setup -s "${SOLO_CLUSTER_SETUP_NAMESPACE}"
          solo cluster-ref config connect --cluster-ref kind-${SOLO_CLUSTER_NAME} --context kind-${SOLO_CLUSTER_NAME}
          solo deployment config create -n "${SOLO_NAMESPACE}" --deployment "${SOLO_DEPLOYMENT}"
          solo deployment cluster attach --deployment "${SOLO_DEPLOYMENT}" --cluster-ref kind-${SOLO_CLUSTER_NAME} --num-consensus-nodes 1
          solo keys consensus generate --gossip-keys --tls-keys --deployment "${SOLO_DEPLOYMENT}"
          solo consensus network deploy --deployment "${SOLO_DEPLOYMENT}" --application-properties "${APP_PROPERTIES_PATH}"
          solo consensus node setup --deployment "${SOLO_DEPLOYMENT}" --local-build-path ./hedera-node/data
          solo consensus node start --deployment "${SOLO_DEPLOYMENT}"
          solo mirror node add --deployment "${SOLO_DEPLOYMENT}" --cluster-ref kind-${SOLO_CLUSTER_NAME} --enable-ingress --pinger
          solo relay node add --deployment "${SOLO_DEPLOYMENT}" -i node1 --dev
          solo ledger account create --deployment "${SOLO_DEPLOYMENT}" --dev --hbar-amount "${TEST_ACCOUNT_HBAR_AMOUNT}" --private-key --set-alias --ecdsa-private-key "${TEST_ACCOUNT_ECDSA_PRIVATE_KEY_DER_1}"
          solo ledger account create --deployment "${SOLO_DEPLOYMENT}" --dev --hbar-amount "${TEST_ACCOUNT_HBAR_AMOUNT}" --private-key --set-alias --ecdsa-private-key "${TEST_ACCOUNT_ECDSA_PRIVATE_KEY_DER_2}"
          solo ledger account create --deployment "${SOLO_DEPLOYMENT}" --dev --hbar-amount "${TEST_ACCOUNT_HBAR_AMOUNT}" --private-key --set-alias --ecdsa-private-key "${TEST_ACCOUNT_ECDSA_PRIVATE_KEY_DER_3}"

      - name: Run the tests
        if: ${{ steps.run_solo.outcome == 'success' }}
        run: |
          npx hardhat test --network local
        working-directory:  evm-testing/system-contract-testing

      - name: Stop solo
        run: |
          kind delete cluster -n ${{ env.SOLO_CLUSTER_NAME }}
